    - name: Installation de MySQL mariadb
      yum: name={{ item }} update_cache=yes state=latest
      loop: "{{ modulessql }}"

    - name: Démarrage de mariadb
      systemd: name=mariadb state=started enabled=yes
 
    - name: Ajout user root
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ MDProot }}'
        state: present
 
    - name: Création BDD Wordpress
      mysql_db:
        name: "{{ db }}"
        state: present
        login_user: root
        login_password: "{{ MDProot }}"
 
    - name: Creation user Wordpress
      mysql_user:
        name: "{{ userwp }}"
        password: "{{ passwordwp }}"
        priv: "{{ db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ MDProot }}"