- name : Installer wget
  yum: 
    name: wget

- name: télécharger repel
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=./


- name: télécharger remirepo
  get_url: url=https://rpms.remirepo.net/enterprise/remi-release-7.rpm dest=./
  
- name: rpm
  command: rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm
  

- name: installer yum-utils
  yum: 
    name: yum-utils

- name : Activer remirepo
  command: yum-config-manager --enable remi-php74

- name: yum update
  yum: name=* state=latest


- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ modulesphp }}"
