    - name: Téléchargement de Wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ URL }}"
        remote_src: yes
        creates: "/var/www/{{ URL }}/wordpress"
 
    - name: Attribution du fichier
      file:
        path: "/var/www/{{ URL }}"
        state: directory
        recurse: yes
        owner: apache
        group: apache
 
    - name: Permissions sur les dossiers
      shell: "/usr/bin/find /var/www/{{ URL }}/wordpress/ -type d -exec chmod 750 {} \\;"
 
    - name: Permissions fichiers
      shell: "/usr/bin/find /var/www/{{ URL }}/wordpress/ -type f -exec chmod 640 {} \\;"
 
    - name: Renommage et création du fichier de config
      command: mv /var/www/{{ URL }}/wordpress/wp-config-sample.php /var/www/{{ URL }}/wordpress/wp-config.php creates=/var/www/{{ URL }}/wordpress/wp-config.php
      become: yes
 
    - name: Mise a jour du fichier de config avec les logins DB
      lineinfile:
        path: "/var/www/{{ URL }}/wordpress/wp-config.php"
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
        - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{db}}' );"}
        - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{userwp}}' );"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{passwordwp}}' );"}
     
    - name: Restart httpd service
      systemd: 
        name: httpd 
        state: restarted
      become: yes